name: Build Artifacts

on:
  push:
    branches: [ master, ci-test ]
  workflow_dispatch:

jobs:
  bin:
    strategy:
      matrix:
        # TODO: probably use older ones so that it runs on older ones
        os: [ubuntu-latest]
        subset: [rubygems, freebsd-arm] # This is just the fastest one for quick CI
        #subset: [rubygems, OpenBSD-intel, freebsd-intel, freebsd-arm, linux-intel, linux-arm, linux-risc, linux-odd1]
        #include:
        #  - os: macos-12

    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: '2.6' # JRuby 9.3 is 2.6, which is our minimum version
          bundler-cache: true

      - name: Install autoconf and automake for macOS
        if: matrix.os == 'macos-12'
        run: brew install autoconf automake libtool pkgconfig

      - name: Pull and set up dockcross
        if: matrix.os == 'ubuntu-latest' && matrix.subset != 'rubygems'
        run: cd binary-builders && ./setup.sh
        env:
          BINARY_SET: ${{ matrix.subset}}

      - name: Install dependencies
        run: bundle install

      - name: Build binary & Gems
        run: bundle exec rake ${{ matrix.os == 'ubuntu-latest' && matrix.subset != 'rubygems' && 'ci-subset-run' || 'ci-run' }}
        env:
          BINARY_SET: ${{ matrix.subset}}

      - name: Attach shared libraries
        uses: actions/upload-artifact@v4
        if: matrix.os != 'ubuntu-latest' || matrix.subset != 'rubygems'
        with:
          name: shared-libraries-${{ matrix.os }}-${{ matrix.subset || 'any' }}-part
          path: ci-output/lib/
          if-no-files-found: error 

      - uses: actions/upload-artifact@v4
        name: Attach gems
        with:
          name: part-gems-${{ matrix.os }}-${{ matrix.subset || 'any' }}
          path: ci-output/pkg/
          if-no-files-found: error

  build-fat-java:
    needs: bin
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: '2.6' # JRuby 9.3 is 2.6, which is our minimum version
          bundler-cache: true

      # grab mac and linux libraries that were built in the last section
      - uses: actions/download-artifact@v4
        with:
          pattern: shared-libraries-*-part
          merge-multiple: true
          path: ci-output/lib/
      - uses: actions/upload-artifact@v4
        name: Attach Libs
        with:
          name: shared-libraries
          path: ci-output/lib/
          if-no-files-found: error

      - name: Install dependencies
        run: bundle install

      - name: Build binary & Gems
        run: bundle exec rake ci-java

      # merge all gems to one artifact
      - uses: actions/download-artifact@v4
        with:
          pattern: part-gems-*
          merge-multiple: true
          path: ci-output/pkg/
      - uses: actions/upload-artifact@v4
        name: Attach gems
        with:
          name: all-gems
          path: ci-output/pkg/
          if-no-files-found: error



  specs-posix:
    runs-on:  ubuntu-latest # TODO: macos too?

    # less doesn't work (and thus tests fails) unless TERM is set. Not set on GHA by default
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: '2.6' # JRuby 9.3 is 2.6, which is our minimum version
          bundler-cache: true

      - name: Install Less
        run: sudo apt update && sudo apt install -y less

      - name: Install dependencies
        run: bundle install

      - name: Build binary & Gems & Run tests
        run: bundle exec rake ci-test

  specs-win32:
    runs-on:  windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: '2.6' # JRuby 9.3 is 2.6, which is our minimum version
          bundler-cache: true

      - name: Build engine-hacks
        run: bundle install && rake install
        working-directory: ./engine-hacks

      - name: Build subspawn-common
        run: bundle install && rake install
        working-directory: ./subspawn-common


      - name: Install dependencies
        run: bundle install
        working-directory: ./subspawn-win32

      - name: Test Gem
        run: bundle exec rspec
        working-directory: ./subspawn-win32

# TODO:
#https://github.com/kouki-h/linux_cross_openbsd/blob/main/Makefile
#https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
